#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename "$0") [-p] [-a] [-s <systems>] [-C] PR_NUMBER"
  echo "  -p: Post the result to GitHub"
  echo "  -a: Approve the PR"
  echo "  -s: Specify systems (default: all)"
  echo "  -C: Enable CUDA support"
}

# Array of key = value strings
extra_config=()
approve_pr=""
post_result=""

while getopts ":aps:C" opt; do
  case $opt in
    p)
      post_result="--post-result"
      ;;
    a)
      approve_pr="--approve-pr"
      ;;
    C)
      extra_config+=("cudaSupport = true;")
      ;;
    s)
      systems="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# Default systems if not specified
systems=${systems:-"x86_64-linux aarch64-linux aarch64-darwin"}

# join extra_config array into a single string separated by ;
extra_config_str=$(IFS=' '; echo "${extra_config[*]}")

# if extra_config_str is not empty, add it to the extra-nixpkgs-config
if [ -n "$extra_config_str" ]; then
  extra_config_arg="--extra-nixpkgs-config={ ${extra_config_str} }"
else
  extra_config_arg=""
fi

NP=${NP:-"nixpkgs-review"}
cmd=(
  "$NP"
  pr "$@"
  --no-shell
)
if [ -n "$extra_config_arg" ]; then
  cmd+=("$extra_config_arg")
fi
if [ -n "$post_result" ]; then
  cmd+=("$post_result")
fi
if [ -n "$approve_pr" ]; then
  cmd+=("$approve_pr")
fi
cmd+=(--systems="${systems}")

if [ -n "${NR_BUILDERS:-}" ]; then
  cmd+=(--build-args="--builders \"${NR_BUILDERS}\"")
fi

"${cmd[@]}"
