#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename "$0") [-p] [-a] [-t] [-i <PR_NUMBER>]... [-s <systems>] [-C] PR_NUMBER"
  echo "  -p: Post the result to GitHub"
  echo "  -a: Approve the PR"
  echo "  -t: Build tests associated with changed packages"
  echo "  -i: Include a dependent PR (can be passed multiple times)"
  echo "  -s: Specify systems (default: all)"
  echo "  -C: Enable CUDA support"
}

# Array of key = value strings
extra_config_values=()
included_prs=()
review_options=()

while getopts ":apti:s:C" opt; do
  case $opt in
    p)
      review_options+=("--post-result")
      ;;
    a)
      review_options+=("--approve-pr")
      ;;
    t)
      review_options+=("--tests")
      ;;
    i)
      included_prs+=("--include-pr" "$OPTARG")
      ;;
    C)
      extra_config_values+=("cudaSupport = true;")
      ;;
    s)
      systems="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument" >&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# Default systems if not specified
systems=${systems:-"x86_64-linux aarch64-linux aarch64-darwin"}

# Join extra_config_values into a single Nix attribute-set body.
extra_config_str=$(IFS=' '; echo "${extra_config_values[*]}")

# if extra_config_str is not empty, add it to the extra-nixpkgs-config
if [ -n "$extra_config_str" ]; then
  extra_config_arg="--extra-nixpkgs-config={ ${extra_config_str} }"
else
  extra_config_arg=""
fi

cmd=(
  nixpkgs-review
  pr "$@"
  --no-shell
)
cmd+=("${included_prs[@]}")
if [ -n "$extra_config_arg" ]; then
  cmd+=("$extra_config_arg")
fi
cmd+=("${review_options[@]}")
cmd+=(--systems="${systems}")

if [ -n "${NR_BUILDERS:-}" ]; then
  cmd+=(--build-args="--builders \"${NR_BUILDERS}\"")
fi

"${cmd[@]}"
