{
 "title": "Power",
 "tags": [
  "fana",
  "power",
  "ups",
  "provisioned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "UPSes Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_ups_tools_ups_status{job=~\"nut-.*\",ups=~\".+\",flag=\"OL\"})"
    }
   ]
  },
  {
   "title": "UPSes On Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_ups_tools_ups_status{job=~\"nut-.*\",ups=~\".+\",flag=\"OB\"})"
    }
   ]
  },
  {
   "title": "Lowest Battery Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(network_ups_tools_battery_charge{job=~\"nut-.*\",ups=~\".+\"})"
    }
   ]
  },
  {
   "title": "Shortest Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(network_ups_tools_battery_runtime{job=~\"nut-.*\",ups=~\".+\"}) / 60"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{job=~\"nut-.*\",ups=~\".+\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{job=~\"nut-.*\",ups=~\".+\"} / 60",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{job=~\"nut-.*\",ups=~\".+\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{job=~\"nut-.*\",ups=~\".+\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Current UPS Flags",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{job=~\"nut-.*\",ups=~\".+\",flag=~\"OL|OB|LB|CHRG|DISCHRG\"}"
    }
   ]
  }
 ]
}