{
 "title": "Resolver Health",
 "tags": [
  "dns",
  "fana",
  "provisioned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Resolver Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-dns\"}",
     "legendFormat": "{{resolver_title}}"
    }
   ]
  },
  {
   "title": "DNS Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"blackbox-dns\"}[5m])",
     "legendFormat": "{{resolver_title}}"
    }
   ]
  },
  {
   "title": "Gateway DNS TCP Reachability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-tcp\",probe=\"gateway-dns\"}",
     "legendFormat": "{{probe_title}}"
    }
   ]
  },
  {
   "title": "Gateway DNS TCP Connect Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"blackbox-tcp\",probe=\"gateway-dns\"}[5m])",
     "legendFormat": "{{probe_title}}"
    }
   ]
  }
 ]
}