name: Maximize build space
description: Reuse maximization settings across workflows.
runs:
  using: composite
  steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: easimon/maximize-build-space@v10
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
