{
 "title": "Services",
 "tags": [
  "arr",
  "blackbox",
  "services"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-service\"}",
     "legendFormat": "{{service_title}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"blackbox-service\"}[5m])",
     "legendFormat": "{{service_title}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox-service\"}",
     "legendFormat": "{{service_title}}"
    }
   ]
  }
 ]
}