#!/usr/bin/env python3

import argparse
import json
from pathlib import Path
from urllib.parse import quote, urlparse


def load_lock(path: Path) -> dict:
    with path.open(encoding="utf-8") as lock_file:
        return json.load(lock_file)


def locked_inputs(lock: dict) -> dict[str, dict]:
    nodes = lock["nodes"]
    inputs = {}

    def visit(node_name: str, path: tuple[str, ...], ancestors: set[str]) -> None:
        node = nodes[node_name]
        for name, child_name in node.get("inputs", {}).items():
            if not isinstance(child_name, str) or child_name in ancestors:
                continue

            child = nodes.get(child_name, {})
            child_path = (*path, name)
            if "locked" in child:
                inputs["/".join(child_path)] = child["locked"]
            visit(child_name, child_path, ancestors | {child_name})

    root_name = lock["root"]
    visit(root_name, (), {root_name})
    return inputs


def revision(locked: dict) -> str:
    for key in ("rev", "ref", "url", "path", "narHash"):
        if value := locked.get(key):
            return str(value)
    return "unknown"


def display_revision(value: str) -> str:
    if len(value) >= 12 and all(
        character in "0123456789abcdef" for character in value.lower()
    ):
        return value[:7]
    return value


def github_repository(locked: dict) -> tuple[str, str, str] | None:
    if locked.get("type") == "github":
        return (
            locked.get("host", "github.com"),
            locked["owner"],
            locked["repo"],
        )

    if locked.get("type") != "git" or not (url := locked.get("url")):
        return None

    parsed = urlparse(url.removeprefix("git+"))
    if parsed.hostname != "github.com":
        return None

    parts = parsed.path.removesuffix(".git").strip("/").split("/")
    if len(parts) != 2:
        return None
    return parsed.hostname, parts[0], parts[1]


def gitlab_repository(locked: dict) -> tuple[str, str, str] | None:
    if locked.get("type") != "gitlab":
        return None
    return (
        locked.get("host", "gitlab.com"),
        locked["owner"],
        locked["repo"],
    )


def compare_url(old: dict, new: dict) -> str | None:
    old_revision = old.get("rev")
    new_revision = new.get("rev")
    if not old_revision or not new_revision:
        return None

    old_github = github_repository(old)
    new_github = github_repository(new)
    if old_github and old_github == new_github:
        host, owner, repo = new_github
        return (
            f"https://{host}/{quote(owner)}/{quote(repo)}/compare/"
            f"{quote(old_revision)}...{quote(new_revision)}"
        )

    old_gitlab = gitlab_repository(old)
    new_gitlab = gitlab_repository(new)
    if old_gitlab and old_gitlab == new_gitlab:
        host, owner, repo = new_gitlab
        return (
            f"https://{host}/{quote(owner)}/{quote(repo)}/-/compare/"
            f"{quote(old_revision)}...{quote(new_revision)}"
        )

    return None


def updated_inputs(old_lock: dict, new_lock: dict) -> list[tuple[str, dict, dict]]:
    old_inputs = locked_inputs(old_lock)
    new_inputs = locked_inputs(new_lock)
    updates = []

    for name in sorted(old_inputs.keys() & new_inputs.keys()):
        if old_inputs[name] != new_inputs[name]:
            updates.append((name, old_inputs[name], new_inputs[name]))

    return updates


def render_body(old_lock: dict, new_lock: dict, trigger: str) -> str:
    updates = updated_inputs(old_lock, new_lock)
    lines = ["Automated update of flake inputs.", ""]

    if updates:
        lines.extend(
            [
                "| Input | Update | Diff |",
                "| --- | --- | --- |",
            ]
        )
        for name, old, new in updates:
            old_revision = revision(old)
            new_revision = revision(new)
            comparison = compare_url(old, new)
            diff = f"[Compare]({comparison})" if comparison else "Unavailable"
            lines.append(
                f"| `{name}` | `{display_revision(old_revision)}` → "
                f"`{display_revision(new_revision)}` | {diff} |"
            )
    else:
        lines.append("No flake input revisions changed.")

    lines.extend(["", "Generated by GitHub Actions.", f"Trigger: {trigger}"])
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a pull request body for flake input updates."
    )
    parser.add_argument("old_lock", type=Path)
    parser.add_argument("new_lock", type=Path)
    parser.add_argument("--trigger", required=True)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    body = render_body(load_lock(args.old_lock), load_lock(args.new_lock), args.trigger)
    args.output.write_text(body, encoding="utf-8")


if __name__ == "__main__":
    main()
