from __future__ import annotations

from collections import Counter
from collections.abc import Iterable

from prometheus_client import CollectorRegistry, generate_latest
from prometheus_client.core import GaugeMetricFamily, Metric

from .state import ACTIVE_JOB_STATES, KNOWN_JOB_STATES, State


PREFIX = "host_observability_lidarr_cue_splitter"


def gauge(name: str, documentation: str, value: float) -> GaugeMetricFamily:
    metric = GaugeMetricFamily(f"{PREFIX}_{name}", documentation)
    metric.add_metric([], value)
    return metric


class SplitterCollector:
    def __init__(self, state: State, *, ok: bool, now: float):
        self.state = state
        self.ok = ok
        self.now = now

    def collect(self) -> Iterable[Metric]:
        states = Counter(job.status for job in self.state.jobs.values())
        yield gauge("ok", "Whether the latest service iteration completed successfully.", self.ok)
        yield gauge(
            "last_run_timestamp_seconds",
            "Unix timestamp of the latest iteration.",
            self.now,
        )
        yield gauge(
            "active",
            "Whether a split or import job is active.",
            any(states[state] for state in ACTIVE_JOB_STATES),
        )

        jobs = GaugeMetricFamily(
            f"{PREFIX}_jobs",
            "Number of known jobs by state.",
            labels=["state"],
        )
        for state in sorted(set(states) | KNOWN_JOB_STATES):
            jobs.add_metric([state], states[state])
        yield jobs

        totals = Metric(
            f"{PREFIX}_jobs_total",
            "Jobs handled by result.",
            "counter",
        )
        for result in (
            "success",
            "failed",
            "ignored",
            "manual",
            "source_invalid",
            "source_unavailable",
        ):
            totals.add_sample(
                f"{PREFIX}_jobs_total",
                {"result": result},
                getattr(self.state.totals, result),
            )
        yield totals

        tracks = Metric(
            f"{PREFIX}_tracks_total",
            "Tracks generated by successful jobs.",
            "counter",
        )
        tracks.add_sample(f"{PREFIX}_tracks_total", {}, self.state.totals.tracks)
        yield tracks
        yield gauge(
            "last_job_duration_seconds",
            "Duration of the latest successful job.",
            self.state.last_duration,
        )
        if self.state.last_success is not None:
            yield gauge(
                "last_success_timestamp_seconds",
                "Unix timestamp of the latest successful import.",
                self.state.last_success,
            )


def render_metrics(state: State, *, ok: bool, now: float) -> str:
    registry = CollectorRegistry()
    registry.register(SplitterCollector(state, ok=ok, now=now))
    return generate_latest(registry).decode()
