from __future__ import annotations

import io
import json
from collections.abc import Mapping, Sequence
from pathlib import Path

import pytest
from pydantic import ValidationError

from package_updates.common import CommandResult, Runner, ToolPaths, UpdateError
from package_updates.models import PackageTarget, PackageTargets
from package_updates.packages import (
    CommandPackageBackend,
    PackageMetadata,
    load_targets,
    main,
    parse_update_script,
    selected_targets,
    summary_row,
    update_packages,
    version_text,
)


class FakePackageBackend:
    def __init__(self, metadata: list[PackageMetadata]) -> None:
        self._metadata = iter(metadata)
        self.updated: list[PackageTarget] = []

    def metadata(self, target: PackageTarget) -> PackageMetadata:
        return next(self._metadata)

    def update(self, target: PackageTarget) -> None:
        self.updated.append(target)


class PackageRunner(Runner):
    def __init__(self, update_script: object = None) -> None:
        self.update_script = update_script
        self.calls: list[tuple[tuple[str, ...], Mapping[str, str] | None, bool]] = []

    def run(
        self,
        arguments: Sequence[str],
        *,
        cwd: Path,
        environment: Mapping[str, str] | None = None,
        capture: bool = True,
    ) -> CommandResult:
        del cwd
        command = tuple(arguments)
        self.calls.append((command, environment, capture))
        if len(command) > 1 and command[1] == "build":
            return CommandResult(1)
        if len(command) > 1 and command[1] == "eval":
            expression = command[-1]
            if expression.endswith(".passthru.updateScript"):
                return CommandResult(0, json.dumps(self.update_script))
            values = {
                ".version": "1.0.0",
                ".meta.changelog": "https://github.com/example/demo/releases/tag/v1.0.0",
                ".meta.homepage": "https://github.com/example/demo",
                ".src.rev": "refs/tags/v1.0.0",
            }
            for suffix, value in values.items():
                if expression.endswith(suffix):
                    return CommandResult(0, value)
            return CommandResult(1)
        return CommandResult(0)


TOOLS = ToolPaths(
    nix="nix",
    nix_update="nix-update",
    nix_prefetch_docker="prefetch",
    skopeo="skopeo",
    cosign="cosign",
    select_nodejs="/package/bin/select-nodejs",
)


def test_loads_and_selects_typed_targets(tmp_path: Path) -> None:
    path = tmp_path / "targets.json"
    path.write_text(
        json.dumps(
            {
                "targets": [
                    {"attr": "one", "system": "aarch64-darwin"},
                    {
                        "attr": "two",
                        "system": "aarch64-darwin",
                        "nixUpdateSystem": "x86_64-linux",
                        "nixUpdateArgs": ["--src-only"],
                    },
                ]
            }
        )
    )
    targets = load_targets(path)
    selected = selected_targets(targets, "two")
    assert selected[0].update_system == "x86_64-linux"
    assert selected[0].nix_update_args == ("--src-only",)
    with pytest.raises(UpdateError, match="No package update targets matched"):
        selected_targets(targets, "missing")


def test_updates_package_and_writes_compare_summary(tmp_path: Path) -> None:
    target = PackageTarget(attr="demo")
    backend = FakePackageBackend(
        [
            PackageMetadata(
                version="1.0.0",
                changelog="https://github.com/example/demo/releases/tag/v1.0.0",
                homepage="https://github.com/example/demo",
                source_revision="refs/tags/v1.0.0",
            ),
            PackageMetadata(
                version="1.1.0",
                changelog="https://github.com/example/demo/releases/tag/v1.1.0",
                homepage="https://github.com/example/demo",
                source_revision="refs/tags/v1.1.0",
            ),
        ]
    )
    summary = tmp_path / "nested" / "summary.md"
    stdout = io.StringIO()
    update_packages([target], summary, backend, stdout)
    assert backend.updated == [target]
    assert (
        "| `demo` | `1.0.0 -> 1.1.0` | "
        "[link](https://github.com/example/demo/releases/tag/v1.1.0) | "
        "[compare](https://github.com/example/demo/compare/v1.0.0...v1.1.0) |"
        in summary.read_text()
    )
    assert "Generated by GitHub Actions." in summary.read_text()
    assert "::group::Updating demo" in stdout.getvalue()


def test_summary_falls_back_to_changelog_and_unknown_version() -> None:
    target = PackageTarget(attr="demo")
    row = summary_row(
        target,
        PackageMetadata(changelog="https://github.com/example/demo/releases/tag/v1"),
        PackageMetadata(changelog="https://github.com/example/demo/releases/tag/v2"),
    )
    assert "`unknown`" in row
    assert "compare/v1...v2" in row
    assert version_text("", "2") == "2"


def test_update_script_payloads_are_validated() -> None:
    assert parse_update_script(None, "demo") is None
    assert parse_update_script([], "demo") is None
    assert parse_update_script("update", "demo") == ("update",)
    assert parse_update_script(["update", "--flag"], "demo") == ("update", "--flag")
    with pytest.raises(UpdateError, match="non-string"):
        parse_update_script(["update", 1], "demo")
    with pytest.raises(UpdateError, match="unsupported"):
        parse_update_script({"command": "update"}, "demo")


def test_command_backend_runs_json_update_script_with_selector_environment(tmp_path: Path) -> None:
    runner = PackageRunner(["/store/update", "--flag"])
    backend = CommandPackageBackend(tmp_path, TOOLS, runner)
    target = PackageTarget(attr="demo", nixUpdateSystem="x86_64-linux")
    backend.update(target)
    command, environment, capture = runner.calls[-1]
    assert command == ("/store/update", "--flag")
    assert environment is not None
    assert environment["UPDATE_NIX_ATTR_PATH"] == "demo"
    assert environment["PACKAGE_UPDATES_SELECT_NODEJS"] == "/package/bin/select-nodejs"
    assert capture is False


def test_command_backend_falls_back_to_nix_update_and_reads_metadata(tmp_path: Path) -> None:
    runner = PackageRunner()
    backend = CommandPackageBackend(tmp_path, TOOLS, runner)
    target = PackageTarget(attr="demo", nixUpdateArgs=["--src-only"])
    backend.update(target)
    assert runner.calls[-1][0] == (
        "nix-update",
        "--flake",
        "--system",
        "x86_64-linux",
        "--src-only",
        "demo",
    )
    assert backend.metadata(target).version == "1.0.0"


def test_package_target_file_rejects_unknown_fields() -> None:
    with pytest.raises(ValidationError):
        PackageTargets.model_validate({"targets": [{"attr": "demo", "unknown": True}]})


def test_console_entrypoint_lists_targets(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    (tmp_path / ".git").mkdir()
    (tmp_path / "flake.nix").touch()
    targets_file = tmp_path / "targets.json"
    targets_file.write_text(json.dumps({"targets": [{"attr": "demo", "system": "aarch64-darwin"}]}))
    monkeypatch.chdir(tmp_path)
    assert main(["--targets-file", str(targets_file), "--list-targets"]) == 0
    assert capsys.readouterr().out == "demo\taarch64-darwin\n"


def test_console_entrypoint_reports_missing_target(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    (tmp_path / ".git").mkdir()
    (tmp_path / "flake.nix").touch()
    targets_file = tmp_path / "targets.json"
    targets_file.write_text(json.dumps({"targets": [{"attr": "demo"}]}))
    monkeypatch.chdir(tmp_path)
    assert main(["--targets-file", str(targets_file), "--target", "missing"]) == 1
    assert "No package update targets matched" in capsys.readouterr().err
