{
  imports = [
    ./_mixins/cli
    ./_mixins/codex
    ./_mixins/host.nix
    ./_mixins/internal-pki
    ./_mixins/nix
    ./_mixins/nixpkgs
    ./_mixins/nixpkgs-review
    ./_mixins/secrets
    ./_mixins/ssh
    ./_mixins/stylix
    ./_mixins/terminfo
    ./_mixins/yubi.nix
    ./_mixins/attic
    ./_mixins/flakehub-cache
    ./_mixins/builders
  ];
}
