{
  imports = [
    ./_mixins/attic
    ./_mixins/builders
    ./_mixins/cli
    ./_mixins/codex
    ./_mixins/desktop.nix
    ./_mixins/hardware
    ./_mixins/host
    ./_mixins/internal-pki
    ./_mixins/network
    ./_mixins/nix
    ./_mixins/nixpkgs
    ./_mixins/power
    ./_mixins/remote-control
    ./_mixins/security
    ./_mixins/site
    ./_mixins/ssh
    ./_mixins/stylix
    ./_mixins/terminfo
    ./_mixins/ups
    ./_mixins/wireguard
  ];
}
