{
  imports = [
    ./aerospace.nix
    ./alertmanager.nix
    ./attention-inbox.nix
    ./battery.nix
    ./clock.nix
    ./codex.nix
    ./disk.nix
    ./front-app.nix
    ./github-status.nix
    ./ip-address.nix
    ./jellyfin.nix
    ./network.nix
    ./openai-status.nix
    ./spotify.nix
    ./stock.nix
    ./volume.nix
  ];
}
