{
  imports = [
    ./audiobookshelf
    ./degoog
    ./external-service.nix
    ./home-assistant
    ./houndarr
    ./internal-service.nix
    ./jellyfin
    ./paperless
    ./paperless-gpt
    ./pinepods
    ./public-ingress.nix
    ./romm
    ./seerr
    ./shelfmark
    ./vikunja
    ./watchstate
  ];
}
