name: Checks

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  actions: read
  pull-requests: read

jobs:
  check:
    name: Regular checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare Nix environment
        uses: ./.github/actions/prepare-nix-env

      - name: Run regular checks
        run: make check

  check-nixos:
    name: NixOS tests
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      NIX_CONFIG: system-features = benchmark big-parallel kvm nixos-test
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Prepare Nix environment
        uses: ./.github/actions/prepare-nix-env

      - name: Run NixOS tests
        run: make check-nixos
